### ISSUE TITLE
Provide a Way to Only do Integrity Check.

### ISSUE THREAD

**Issue by zicklag** [nidor1998/s3sync#25]
**Is your feature request related to a problem? Please describe.**
I have a bunch of files on S3 and a folder locally that I want to make sure are in sync. I don't want to re-initiate the entire synchronization, but I want to make sure that the checksums match.

**Describe the solution you'd like**
I would like to be able to somehow run a comparison between my s3 bucket, and the local filesystem, calculating the checksums for all of the local files, and comparing to make sure they match the s3 bucket, and that there are not missing files on either side.

**Describe alternatives you've considered**
This might not need to be a separate command necessarily, if maybe there was a filter that would use the checksums to only copy files that have differing checksums.

**Comment by nidor1998** [comment]
Thanks for the comment.

s3sync integrity check has been done when transferring the object.
And Incremental transfer is done by comparing the modification time or size of the object.
so there is no way to check the integrity of the object before transferring it.

In the amazon s3, the most common way to check the integrity of the object is to compare the ETag of the object in the source and target.
But the ETag of the object is not always the MD5 digest of the object. It depends on how the object is uploaded.

s3sync does not intentionally use the ETag of the object for incremental transfer. because the etag of the object may be different even if the object is the same.

But I know your situation. you want to check the difference based on the checksum of the object before transferring it.

there are some solutions.

1. use the `--dry-run` and `--check-size` option.  
   s3sync does not actually transfer the object and dry run output the list of objects that will be transferred.  
   `--check-size` option checks only the size of the object.

   this is the simplest way to check the size of the object, but it is not integrity check of the object.
   some situations, it is enough.

2. Implement new feature to check etag of the object for incremental transfer.
   But this is not perfect because the etag of the object may be different even if the object is the same.
   It is a bit difficult to know how object is multipart uploaded and its chunk size.
   And if source object exist in local, it takes time to calculate the md5 of the object.

   and it takes time to implement.

**Comment by zicklag** [comment]
Thanks for the reply! I think for my use-case the best solution is probably to use s3sync to do a fresh complete copy, knowing that it will validate integrity as it does the copy, and then use it in the future for incremental updates. It will take time to re-download, but at least I only need to do it once. :+1:

**Comment by nidor1998** [comment]
thanks for the comment.
I will try to implement the feature in the next release.
Because this tool emphasizes the integrity of the object, I think it is necessary to check the integrity of the object without transferring it.

**Comment by nidor1998** [comment]
I've implemented the feature that check ETag(MD5 digest or equivalent) for incremental transfer.
Please use `--check-etag` and `--dry-run` option to meet your requirements.

For example, if you want to check that synchronization is correct, you can use `--check-etag` option.
```bash
s3sync --dry-run --check-etag s3://target-bucket/testdata/ ./testdata/
s3sync --dry-run --check-etag ./testdata/ s3://target-bucket/testdata/ ./testdata/
```

The Amazon S3 ETag is complicated. Please read the following document.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html

If you don't know the chunk size of the multipart upload, you can use `--auto-chunksize` option.
I am not a native English speaker. If you cannot understand my English, please let me know. CoPilot helps me a lot.

I hope this helps you.

**Comment by zicklag** [comment]
Awesome! Thank you very much. I'll try that out. :heart:
