### ISSUE TITLE
Unwrap None

### ISSUE THREAD

**Issue by FredrikNoren** [nidor1998/s3sync#6]
**Describe the bug**
I'm getting this error: `thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/fredrik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/s3sync-0.1.10/src/pipeline/head_object_checker.rs:138:38`

**To Reproduce**
Using s3sync to download from s3 to a local directory

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 0.1.10

**Comment by nidor1998** [comment]
@FredrikNoren 
Thank you for reporting. I will check it.

What we know at this point is that the attempt to get a timestamp of the local file system failed.

**Comment by nidor1998** [comment]
I was able to reproduce it.
This is a special situation that occurs when downloading an object to local disk with a key name ending in "/" and an object size greater than 0 bytes.

This is a difficult case to handle because of incompatibilities between object storage and block device file systems.

s3sync outputs a warning message and skips the download.

This is currently being tested.

**Comment by nidor1998** [comment]
@FredrikNoren 

I Fixed it. Please check it out.

https://github.com/nidor1998/s3sync/releases/tag/v0.1.11
